catalyst-cooperative/pudl-archiver

- README.md
- src/pudl_archiver/cli.py
Just some refactoring I did while I was mucking around making sense of the code.
Basically this just looks at `AbstractDatasetArchiver` and grabs all its subclasses - they need to get `import`ed first before they become registered on the base class, though, hence that weird `__import__` thing.
That makes it so that we can just add the Archiver subclasses and not worry about updating the CLI - which is a trivial worry, but maybe a nice quality-of-life thing to have.
If this seems like not a useful thing I'm happy to close it too - this was mainly for my own learning/orientation.
> Keep CLI choices in sync with AbstractDatasetArchiver.__subclasses__

- src/pudl_archiver/__init__.py
- src/pudl_archiver/cli.py
- src/pudl_archiver/zenodo/api_client.py
Add a `--dry-run` mode so that I can more safely test the automated runs.
* move "actually do archiving" logic into `__init__.py` and out of `cli.py` - in preparation for maybe doing some programmatic access later.
* add `dry_run` attribute to the `ZenodoDepositionInterface` so we can check if we're running dry or wet.
* change `ZenodoDepositionInterface` to the "collect a bunch of IO things to do, then do all the IO in one place" pattern to make dry-run checks easier
I could imagine trying to separate the IO and the logic even more, that would help the testing as well - e.g. some sort of `DepositionDiffer` that can take deposition info from anywhere and produces a changeset, then some sort of `ZenodoThingDoer` that produces deposition info and also applies a changeset. In testing you …
> Add dry run

- .gitignore
- src/pudl_archiver/__init__.py
- src/pudl_archiver/zenodo/api_client.py
I was running into some Zenodo errors and decided to start sending back the `errors` field in the actual request.
I also noticed that the archiver process doesn't exit with a non-zero status if we swallow the exceptions - so I decided to collect all the exceptions and log them at the end - this lets the archiver process actually fail, basically.
Otherwise, there are a few small bug fixes in here that are basically typos.
> Improve error logging and handling

- .github/workflows/run-archiver.yml
- .github/workflows/tox-pytest.yml
- README.md
- src/pudl_archiver/cli.py
- tox.ini
This adds a github action that creates the conda env and runs `pudl_archiver`.
It allows for some parallelism in builds - we can define that via the `dataset_groups` setting on the `job.strategy`.
Some things before this becomes fully "production":
> Github Action to run `pudl_archiver` regularly

- pyproject.toml
- src/pudl_archiver/depositors/__init__.py
- src/pudl_archiver/depositors/zenodo.py
- tests/integration/zenodo_depositor_test.py
This is very much cut-and-paste from the `ZenodoDepositionInterface`, and the code isn't used anywhere outside of the test I just wrote.
I decided to make One Big Test because I didn't want to make a million little depositions on the sandbox environment.
There are a couple logic changes which I'll point out in the actual PR comments.
@zschira - let me know if you'd like to walk through these changes together, +504 is pretty big. Though, again, I think most of this will be pretty familiar to you.
> Create dedicated Zenodo interaction class

- src/pudl_archiver/zenodo/api_client.py
As discussed in #32 we need to apply changes to the deposition before refreshing the `datapackage.json` - this lets us have an up-to-date view of what's in the deposition, what the remote URLs are, etc.
> Apply changes to new deposition before datapackage update

- src/pudl_archiver/depositors/zenodo.py
- src/pudl_archiver/frictionless.py
- src/pudl_archiver/zenodo/api_client.py
- src/pudl_archiver/zenodo/entities.py
- tests/integration/zenodo_depositor_test.py
- tests/integration/zenodo_test.py
This removes all direct Zenodo access from `api_client.py` - which means we should probably reorganize the code now that the code in the `zenodo` directory doesn't directly deal with Zenodo anymore.
There's still plenty of clean-up to do with, e.g., collapsing `ZenodoClient` and `ZenodoDepositionInterface` into one `DepositionTwiddler` class or something better-named - but I think that's the next step here.
> Remove Zenodo from the ZenodoDepositionInterface

- src/pudl_archiver/__init__.py
- src/pudl_archiver/archivers/classes.py
- src/pudl_archiver/zenodo/api_client.py
- tests/integration/zenodo_test.py
- tests/unit/archive_base_test.py
This puts the various initialization/cleanup code that was in `ZenodoClient` into `ZenodoDepositionInterface` and simplifies the calling process by putting the high-level business logic in `ZenodoDepositionInterface.run`.
> ZenodoDepositionInterface / ZenodoClient Unification

- src/pudl_archiver/__init__.py
- src/pudl_archiver/orchestrator.py
- tests/integration/zenodo_test.py
- tests/unit/zenodo_api_test.py
It is the deposition orchestrator now so let's call it that.
I split this out because I was worried doing the rename in the same PR would cause mayhem in the diff view.
Also threw a bunch of TODOs in here to keep notes for the next time we jump into this - I think it's about time to focus on the Dagster stuff.
> Rename now misleadingly-named ZenodoDepositionInterface

- dataset_doi.yaml
- src/pudl_archiver/archivers/epacamd_eia.py
There was a typo in the epacamd_eia id that came up in #54. I mean to fix this in my last round of fixes, but apparently forgot.
> Fix epacamd_eia datasource id

- src/pudl_archiver/archivers/eia176.py
This archiver grabs all EIA 176 reports in [one .zip file](https://www.eia.gov/naturalgas/ngqs/all_ng_data.zip) and archives them in Zenodo. This PR is linked to a PR in the pudl repo, which adds EIA176 to `sources.py`. To test before this gets merged into pudl/dev, you'll need to update pyproject.toml to point to the eia176 branch of the pudl repo. An example sandbox output can be found [here](https://sandbox.zenodo.org/record/1155188).
This data is listed in our [Future Datasets documentation](https://catalystcoop-pudl.readthedocs.io/en/dev/data_sources/wip_future.html#phmsa-natural-gas-pipelines) and our [Sloan New Data Plan](https://docs.google.com/document/d/1q9J49sDbwFNsbfk31p_sU0dSKiyq5TiO/edit#heading=h.gjdgxs).
> Add EIA 176 archiver

- src/pudl_archiver/archivers/classes.py
- src/pudl_archiver/archivers/ferc/xbrl.py
- tests/unit/archive_base_test.py
- tests/unit/xbrl_test.py
Since the `xbrl` and the `AbstractDatasetArchiver` uses of session are slightly different, I made two different utility functions for retries. Figured that'd be a little better than using a relatively unpopular library like aiohttp-retry.
Not sure if 2 -> 4 -> 8 -> 16s is the right set of exponential backoff.
> Add retry logic to all session.gets in data download process

- README.md
- src/pudl_archiver/orchestrator.py
This PR fixes the `--dry-run` CLI option, which was previously skipping applying changes to a draft deposition, but then trying to publish that unchanged deposition, which was causing failures.
Closes #62
> Fix `--dry-run` option

- src/pudl_archiver/archivers/eiawater.py
This PR expands the regex we're using to identify links to archive on the EIA cooling water page, since they're using new filenames for 2021 and the old regex wasn't catching them.
Closes #77
> Update EIA Water link regex for 2021 files

- .github/workflows/run-archiver.yml
- dataset_doi.yaml
- src/pudl_archiver/archivers/mshamines.py
- src/pudl_archiver/archivers/phmsagas.py
Tweak the archive filenames slightly to match naming patterns from other archivers.
Add new production DOIs for:
* `eia176`
* `eiawater`
* `mshamines`
* `phmsagas`
I used these archivers to initialize archives on the production Zenodo site, and also updated a bunch of other archivers (See #79). However, I didn't update the FERC archives because of the issue with unique IDs in the RSS feeds described in #73.
Closes #79
> Standardize filenames and add production DOIs

- src/pudl_archiver/archivers/epacamd_eia.py
This PR updates the `epacamd_eia` archiver to archive 2021 data by downloading a zip of our forked crosswalk repo, which contains the 2021 outputs.
> Point crosswalk archive at our mirror with 2021 outputs

- src/pudl_archiver/archivers/ferc/ferc2.py
- src/pudl_archiver/archivers/ferc/ferc6.py
- src/pudl_archiver/archivers/ferc/ferc60.py
- src/pudl_archiver/archivers/ferc/ferc714.py
What it says on the tin. Make sure to use lowercase values for `data_format` partition.
> Make partitions (data_format) lowercase when building archives

- src/pudl_archiver/archivers/eia860.py
Add regex to identify early release data links that were previously unmarked. Now contain ER in the link name: `eia860-2022ER.zip`
> Update eia860 regex

- src/pudl_archiver/__init__.py
- src/pudl_archiver/archivers/classes.py
- src/pudl_archiver/archivers/eia860.py
- src/pudl_archiver/archivers/eia860m.py
- src/pudl_archiver/archivers/eia861.py
- src/pudl_archiver/archivers/eia923.py
- src/pudl_archiver/archivers/eiawater.py
- src/pudl_archiver/archivers/epacems.py
- src/pudl_archiver/archivers/ferc/ferc1.py
- src/pudl_archiver/archivers/ferc/ferc2.py
- src/pudl_archiver/archivers/ferc/ferc6.py
- src/pudl_archiver/archivers/ferc/ferc60.py
- src/pudl_archiver/archivers/ferc/ferc714.py
- src/pudl_archiver/cli.py
- tests/unit/archive_base_test.py
- tests/unit/eia_archiver_test.py
- tests/unit/eiawater_test.py
- tests/unit/ferc_archiver_test.py
When investigating the FERC 2022 data for catalyst-cooperative/pudl#2766, I found that it was hard to "Just get the raw 2022 FERC 1 XBRL data and save it somewhere on disk where I can mess with it."
This adds:
* yearly filtering for the datasets where that was easy to do
* ability to dump the downloaded file to a non-temporary directory
> Download data from specific years to a specific location

- src/pudl_archiver/__init__.py
- src/pudl_archiver/archivers/classes.py
- src/pudl_archiver/archivers/eia861.py
- tests/unit/pudl_archiver_test.py
This PR does a collection of things:
1) Fixes an issue with the temporary directory from #139 
2) Adds an early release suffix to the regex command to include 2022 early release data in the archive download
3) Fixes an issue with the `--summary-file` flag, which was writing empty files.
Jumped the gun a bit and used this to run both sandbox and production before review, but works as expected.
> Update EIA 861 archiver to capture 2022 early release data

- .github/workflows/run-archiver.yml
- src/pudl_archiver/archivers/classes.py
- src/pudl_archiver/archivers/ferc/ferceqr.py
- src/pudl_archiver/depositors/zenodo.py
- src/pudl_archiver/orchestrator.py
- src/pudl_archiver/utils.py
- src/pudl_archiver/zenodo/entities.py
- tests/unit/archive_base_test.py
This script archives FERC EQR data from two sources: [2002-2013](https://www.ferc.gov/download-database) and [2014-present](https://eqrreportviewer.ferc.gov/). Technically, the code _should_ work: it produces the expected URLs for each resource, and sends them to the `download_zipfile()` method. However, two issues will frustrate the easy use of this archiver and should be dealt with more creatively.
1. Exceptionally slow download times from FERC. As FERC notes on their website:
> Due to the large size of the database, only three users are allowed to download simultaneously at any time. Because downloading may take a long time, it will likely work best if scheduled during off-peak hours, such as Sundays or at night.
Indeed, running this script generally results in timeout errors. Because …
> FERC EQR Archiver

- src/pudl_archiver/archivers/ferc/ferc1.py
- src/pudl_archiver/archivers/ferc/ferc2.py
- src/pudl_archiver/archivers/ferc/ferc6.py
- src/pudl_archiver/archivers/ferc/ferc60.py
- src/pudl_archiver/archivers/ferc/ferc714.py
- src/pudl_archiver/archivers/ferc/xbrl.py
- tests/unit/ferc_archiver_test.py
This PR adjusts the layout of FERC XBRL archives. It moves the taxonomies to be their own resource instead of bundled with a year of filings.
> Xbrl taxonomy

- src/pudl_archiver/orchestrator.py
Current archiving infrastructure allows keywords for Zenodo datasets to be null. This poses a problem when using the datastore. This PR adds an assertion that mandates keywords for new archives to prevent this issue. You can test it by running it on MSHA, PHMSA, or EIA Water data with a `--initialize` flag.
> When making a new dataset, assert keywords exist

- .github/workflows/run-archiver.yml
- .github/workflows/tox-pytest.yml
- .gitignore
- environment.yml
- pyproject.toml
- tests/unit/zenodo_entities_test.py
While trying to debug a dependency update CI failure, I noticed that we still had this repo pinned to depending on the `catalystcoop.pudl@pre-dagster` branch 😲 
So I did some updates:
* Point PUDL dependency at `catalsytcoop.pudl@dev`
* Use Python 3.11
* Switch to using the newer and maintained `mamba-org/setup-micromamba` action both in the `tox-pytest` and `run-archiver` workflows.
* Updated one test that was expecting an old FERC Form 1 title and not getting it.
> Update to depending on PUDL development branch.

- .gitignore
- .pre-commit-config.yaml
- environment.yml
- pyproject.toml
- src/pudl_archiver/__init__.py
- src/pudl_archiver/archivers/classes.py
- src/pudl_archiver/archivers/epacems.py
- src/pudl_archiver/archivers/ferc/xbrl.py
- src/pudl_archiver/cli.py
- src/pudl_archiver/depositors/zenodo.py
- src/pudl_archiver/frictionless.py
- src/pudl_archiver/orchestrator.py
- src/pudl_archiver/utils.py
- src/pudl_archiver/zenodo/entities.py
- tests/conftest.py
- tests/integration/zenodo_depositor_test.py
- tests/integration/zenodo_test.py
- tests/unit/archive_base_test.py
- tests/unit/archive_validate_test.py
- tests/unit/eia_archiver_test.py
- tests/unit/eiawater_test.py
- tests/unit/ferc_archiver_test.py
- tests/unit/frictionless_test.py
- tests/unit/pudl_archiver_test.py
- tests/unit/utils_test.py
- tests/unit/zenodo_api_test.py
- tox.ini
I went in to try and investigate the inclusion of draft URLs in the `datapackage.json` metadata, and discovered that there were conflicts between the dependencies in `pudl-archiver` and the main PUDL repo, so it could never solve the environment.
While resolving that I went ahead and switched over to using the Ruff linter in this repo and fixed some issues it highlighted.
There's still one failing unit test though, which is maybe related to some mocking? Which I don't really understand. I tried to switch it from mocking `open` to mocking `Path.open` which seems to have worked, but this seems to have messed up another call to open. :-/ 
```
pytest tests/unit/pudl_archiver_test.py::test_archive_datasets
```
I tried to do a dry-run of archiving the `eia861` to see if the draft paths were …
> Set up Ruff and fix dependency conflicts with PUDL repo.

- src/pudl_archiver/cli.py
- src/pudl_archiver/depositors/zenodo.py
- src/pudl_archiver/frictionless.py
- src/pudl_archiver/orchestrator.py
- src/pudl_archiver/zenodo/entities.py
- tests/integration/zenodo_depositor_test.py
- tests/integration/zenodo_test.py
- tests/unit/frictionless_test.py
- tests/unit/zenodo_entities_test.py
The Zenodo backend migration has resulted in changed behaviors of the API, even without the full API migration noted in #184. These changes are accommodated here:
- `get_new_version` endpoint no longer returns the `version` consistently, so we get it from the earlier `GET` response metadata.
- The `delete_deposition` method has a new behavior that errors our existing tests, and behavior has been changed to catch errors in response to deletion
- changes a few tests to reflect changed error messages and behaviors around deletion, `get_new_version`
- adds a `canonical` method for file links that removes any `api`, `draft` or `content` references to get the most stable version of a file's link
> Minor fixes to work with new Zenodo backend

- dataset_doi.yaml
- src/pudl_archiver/archivers/validate.py
- src/pudl_archiver/depositors/zenodo.py
- src/pudl_archiver/orchestrator.py
- src/pudl_archiver/zenodo/entities.py
- tests/integration/zenodo_depositor_test.py
- tests/unit/zenodo_entities_test.py
* handling deposition deletion flakiness a little more gracefully
* wrongly assumed that zenodo URL would always have a subdomain e.g. `https://www.zenodo.org` - but instead sometimes it's `https://zenodo.org`. Fixed regex.
* update test to allow for slow updates on zenodo side
> Prod Zenodo tweaks

- .github/workflows/run-archiver.yml
- .gitignore
- tests/unit/pudl_archiver_test.py
Also, only archive the specific datasets requested by RMI... should be easy to add the rest back in later, but for now I want to keep the system small.
Closes catalyst-cooperative/pudl#3066
> Update schedule to be quarterly

- dataset_doi.yaml
- src/pudl_archiver/archivers/phmsagas.py
Adds a multi-year `years` partition to the datapackage which includes a list of all years included in a multi-year ZIP file, and adds a new dataset while we're at it.
See sample sandbox archive [here](https://sandbox.zenodo.org/records/1981).
After #177 merged, we should run a production archive and check that `datapackage.json` is valid using `frictionless`.
> PHMSA archiver: add multi-year years partition, add new dataset

- src/pudl_archiver/orchestrator.py
- tests/integration/zenodo_test.py
Sometimes, e.g. when you've updated how you generate the `path` and `remote_url` fields of `datapackage.json`, you want to update `datapackage.json` EVEN THOUGH there were no changes to the files themselves.
Other times, you don't want to update `datapackage.json` because the difference between the old and new `datapackage.json` is just creation time / version number / deposition ID incrementing between the two versions.
Made some refactoring / cleanup changes while I was in here banging my head against how and when to do things:
* in-lined some very straightforward methods that were only being used in one place
* broke out helper functions from `run()` body to better communicate the flow of the orchestrator
* stopped bailing out immediately after changeset generation on dry run, in an …
> Update datapackage.json, but only sometimes

- src/pudl_archiver/archivers/phmsagas.py
- src/pudl_archiver/archivers/validate.py
With PHMSA, we use both integers (former) and lists of integers (current) as our partitions. This breaks the existing checks on `PartitionDiff`. This tiny PR allows more types for partitions.
Also fixes incorrect year range on the PHMSA archiver - `present` files should point to last year's data, while `_2003` should contain data up until 2003, e.g.
> Allow integers and lists for partition pydantic validation, fix PHMSA bug

- src/pudl_archiver/__init__.py
- src/pudl_archiver/depositors/zenodo.py
- src/pudl_archiver/frictionless.py
- src/pudl_archiver/orchestrator.py
- src/pudl_archiver/zenodo/entities.py
- tests/integration/zenodo_test.py
We talked a big game about wanting to stop using `self.deposition`, `self.new_deposition` everywhere.
It wasn't such a bad change in the end!
In the future I think we can try to split up the concept of a "Zenodo `Deposition`" (the API response object) from a "PUDL Dataset Version" (some sort of concept that *we* have). That could look something like:
```python
class DatasetVersion:
rec_id: int
...
class PublishedDataset:
def from_doi(concept_doi) -> PublishedDataset:
...
def get_draft_version(self) -> DraftDataset:
class DraftDataset(Dataset):
def sync_with_resources(self, resources) -> DraftDataset:
original = PublishedDataset.from_doi(doi)
draft = original.get_draft_version()
draft.sync_with_resources()
```
That would make the `ZenodoDepositor` much more of a "thin shell around literal …
> Push some state to `orchestrator.run()`

- .github/workflows/run-archiver.yml
Closes catalyst-cooperative/pudl#3068.
Now that we have automatically running archivers that send stuff to Slack when they succeed/fail and point us towards places we can actually approve them, we should point these at production!
> Point automated archiver at production Zenodo.

- dataset_doi.yaml
- src/pudl_archiver/archivers/epacems.py
- src/pudl_archiver/depositors/zenodo.py
- src/pudl_archiver/orchestrator.py
- tests/integration/zenodo_test.py
As part of #230 I found that we were running into flakiness when deleting drafts and re-creating them to guarantee a fresh starting state for our archiver - i.e., one where the new draft matches the existing deposition exactly.
But, I realized that we don't need to guarantee a fresh starting state and can ditch a lot of that logic - and the less logic we have that tries to deal with Zenodo state, the less that instability in that behavior will affect us 🥲 
This doesn't fix #230 completely, because we seem to also sometimes fail to download from CEMS, but should improve our Zenodo interaction somewhat.
> Don't do a weird song-and-dance to guarantee a fresh draft.

- dataset_doi.yaml
- src/pudl_archiver/archivers/classes.py
- src/pudl_archiver/archivers/eia860.py
- src/pudl_archiver/archivers/eia860m.py
- src/pudl_archiver/archivers/epacems.py
- tests/unit/eia_archiver_test.py
Closes #239 - we can get around the 100-file limit on Zenodo by zipping things into fewer files.
Currently stacked on top of `multi-zip-cems` but could easily just get rebased on top of `main` once `stop-discarding-drafts` gets merged.  Though the `add_to_archive` method would maybe cause a conflict... but it should be all pretty straightforward.
We'll have to handle the new partition format downstream - I think @cmgosnell had volunteered for this?
I ran `pudl_archiver --datasets eia860m  --sandbox --only-years 2020 2021` and got [this output](https://sandbox.zenodo.org/records/13857). Good signs:
- partitions in `datapackage.json` look good and include all the `202X-XX` months we expect
- zip files are ~90 MB each and include 12 8MB files each - makes sense, xlsx files are already …
> Zip EIA 860M files by year

- scripts/make_slack_notification_message.py
Archive-notify failed due to the 3001 character limit:
https://github.com/catalyst-cooperative/pudl-archiver/actions/runs/7265550885/job/19795893314
I made the output a bit less verbose, truncated the output, and added the fallback `"text"` field mentioned in the error message above.
Tested by running 
```
pudl_archiver --datasets eia860m  --sandbox --only-years 2018 2020 --summary-file eia860m.json
```
And then 
```
./scripts/make_slack_notification_message.py --summary-files *-summary.json | pbcopy
```
And then pasting that output into https://app.slack.com/block-kit-builder/ (removing the top-level `text` field) to verify that it looked fine.
> Make message more compact & limit it to 3000 characters

- .github/workflows/run-archiver.yml
They made artifacts immutable in the upload/download-artifacts@v4 versions.
Just naively applying the [migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact) here.
> Update artifact uploads due to breaking changes in v4

- README.md
Closes [issue 3119](https://github.com/catalyst-cooperative/pudl/issues/3119)) in the main PUDL repo. Adds documentation describing additional manual steps/spotchecking to validate an archive once automatically made.
> Outline manual steps for archive review

- src/pudl_archiver/archivers/classes.py
- src/pudl_archiver/utils.py
- tests/unit/utils_test.py
The MD5 checksums of zipfiles we make (CEMS, 860M) change even when the files zipped in them stay the same. This is because the file modification time changes. This PR manually fixes the `datetime` of files when we add them to a zipfile repository. 
To test:
`pudl_archiver --datasets eia860m --sandbox --initialize --summary-file test.json --only-years 2015`
Run twice and compare checksums on the zipped file for each repository.
> Force zipfiles to be identical by fixing timestamps of zipped files

- src/pudl_archiver/archivers/phmsagas.py
To make the excel extractor in `pudl` work consistently with the PHMSA data, update the `years` partition to `year` to match all other partitions. See draft dataset at: https://zenodo.org/deposit/10493790
> Change PHMSA partitions to use `year` instead of `years`

- src/pudl_archiver/archivers/phmsagas.py
PHMSA data has a `_present` filename that doesn't provide information about the data end date. Because the data isn't released right at the end of the year, our prior "assume from the prior year" assumption doesn't hold at the beginning of the year. To make this more robust, look inside all `_present` files and get the last year's worth of data from the file name contained inside, by sorting the file names and getting the year from the last portion of the filename string. Draft archive here: https://zenodo.org/uploads/10493790
> When PHMSA data has `_present` in file name, make partitions actually reflect years of data available correctly.

- .github/workflows/run-archiver.yml
- environment.yml
The issue found in #256 has been fixed through the creation of a new archive (v 3.0). This PR simply adds the `eia_bulk_elec` dataset to the monthly scheduled archiver run, as this dataset is relatively regularly updated. It also bumps `fiona` to `>=1.9.5` to match the version in PUDL and fix a CI issue.
> Add `eia_bulk_elec` to monthly automated archiver runs

- src/pudl_archiver/archivers/validate.py
- tests/unit/archive_base_test.py
This PR addresses #245:
- adds `test_zip()` into the zipfile file check method.
- updates the validation summary to include file checks by default
- adds a test to ensure bad zipfiles fail our file check
> Update zipfile type check validation and add file checks into summary JSON files

- pyproject.toml
Reverts catalyst-cooperative/pudl-archiver#266. See discussion in that PR, we've forcibly pinned the `pudl` repo to be <5 for now.
> Revert "Update frictionless requirement from <5,>=4.40 to >=4.40,<6"

- .github/workflows/run-archiver.yml
- scripts/make_slack_notification_message.py
- src/pudl_archiver/__init__.py
- src/pudl_archiver/archivers/classes.py
- src/pudl_archiver/archivers/eia/eia176.py
Closes #279.
Fixes the current blocking of the EIA 176 archiver (only) from downloading all fields of 176 data.
Added rotating `user-agent`s to EIA 176 archiver, improved error handling of `get_json`. Added a log to enable header tracing from `aiohttp` calls.
Run `run-archiver` GHA and verify that 176 archiver runs successfully.
```[tasklist]
```
> Fix GHA runs for EIA 176

- .github/workflows/run-archiver.yml
Addresses part of #285.
Zenodo fixed the backend issue that was preventing us from making new `eiawater` archives (see #276 and #285). Now, let's add it to the archiver.
Manually made a new `eiawater` archive with `--refresh-metadata` to fix keyword issues, and added it to the GHA action.
Run the GHA action.
```[tasklist]
```
> Add `eiawater` to automatic archiver

- .github/workflows/run-archiver.yml
- README.md
- dataset_doi.yaml
- src/pudl_archiver/archivers/eia/nrelatb.py
- src/pudl_archiver/archivers/validate.py
- src/pudl_archiver/cli.py
- src/pudl_archiver/frictionless.py
Closes #294.
Archives NREL ATB.
Point directly to download link for NREL ATB data, and add archiver. We aren't using the `s3://` link to avoid having to import `boto3` and deal with `boto3` and `asyncio` incompatibilities. Also adds a validation method for Parquet filetypes.
Inspect the sandbox archive: https://sandbox.zenodo.org/records/37905
```[tasklist]
```
> Archive NREL ATB for Electricity

- .github/workflows/run-archiver.yml
- README.md
- dataset_doi.yaml
- src/pudl_archiver/archivers/eia/eia930.py
- src/pudl_archiver/archivers/validate.py
- src/pudl_archiver/cli.py
- tests/unit/archive_validate_test.py
Closes #295 
Archives raw EIA 930 data.
- Zips files into one zipfile per half-year, drawing on the file list provided by EIA. 
- Adds a CSV validation method. 
- Adds DOIs to `dataset.doi`
- Adds archive to GHA
- Switch from `2018h1` to `2018half1` for partition to avoid confusion with "hours" shorthand
Review [sandbox archive](https://sandbox.zenodo.org/records/38410) and [draft production archive](https://zenodo.org/records/10840078?preview=1), attempt to make archive.
```[tasklist]
```
> Archive EIA 930 data

- src/pudl_archiver/frictionless.py
- src/pudl_archiver/orchestrator.py
- tests/unit/archive_base_test.py
- tests/unit/archive_validate_test.py
We no longer use the `remote_url` field in our archives, and instead leave the `path` field pristine and infer the local paths, so we should stop inserting the cruft into new archives.
- I removed the `remote_url` field from my handmade `gridpathratk` archive and it worked fine.
```[tasklist]
```
> Stop generating deprecated `remote_url` metadata field.

- .github/workflows/run-archiver.yml
- src/pudl_archiver/archivers/ferc/xbrl.py
Closes #285 .
FERC archivers were failing with
```
TypeError: Constructor parameter should be str
```
Which we thought was related to some other error messages earlier about
```
Unsuccessful renaming of downloaded file to active file /Users/dazhong-catalyst/Library/Caches/Arelle/https/ecollection.ferc.gov/taxonomy/form60/2022-01-01/schedules/ScheduleTemporaryCashInvestments/sched-105_2022-01-01_pre.xml                             
Please remove with file manager.
```
But actually *those* errors were due to concurrency issues with arelle, and we already handled them with retries. The true issue was that `aiohttp.ClientSession.get()` wants a `str` or [`yarl.URL`](https://yarl.aio-libs.org/en/stable/api/#yarl.URL) which is different from the …
> Fix failing FERC archivers

- environment.yml
- pyproject.toml
- tests/unit/archive_base_test.py
Update the PUDL archivers to use Python 3.12, so they are compatible with the main PUDL package.
Currently one failing test.... not sure why!
```console
pytest tests/unit/archive_base_test.py::test_download_file
```
```py
@pytest.mark.asyncio
async def test_download_file(mocker, tmp_path):
"""Test download_file.
Tests that expected data is written to file on disk or in memory. We use Catalyst's
README.md file to ensure that downloads produce the same content as a direct GET.
"""
def _ground_truth_download(url):
return requests.get(url, timeout=1000).content
url = "https://github.com/catalyst-cooperative/pudl-archiver/blob/main/README.md"
file_content = _ground_truth_download(url)
archiver = MockArchiver(None)
async with ClientSession() as session:
archiver.session = session
file = …
```
> Update to use Python 3.12

- .github/ISSUE_TEMPLATE/monthly-archive-update.md
Make monthly archive updates faster by creating a template for review. The next step will be to connect this to the GHA so this issue is automatically created after each monthly run.
See #314 for an example of how this looks as a rendered issue.
> Update issue templates for monthly dataset review

- dataset_doi.yaml
- src/pudl_archiver/archivers/phmsagas.py
Closes #319
Fixes download failure due to double slash, and handles `2023_DELAYED.xlsx` file format by updating `file_years` method to use regex instead of split.
Run the PHMSA archiver.
```[tasklist]
```
> Update PHMSA sandbox doi and fix PHMSA archiver

- pyproject.toml
- tests/unit/frictionless_test.py
* A step toward https://github.com/catalyst-cooperative/pudl/issues/3293
* Update to `frictionless>=5,<6` and make minor syntax adjustments related to datapackage descriptor validation.
* Note that the draft PR points at the `frictionless-5` branch of PUDL to verify that everything is working. When https://github.com/catalyst-cooperative/pudl/pull/3569 is merged this pointer should revert to pointing at the `main` branch of PUDL.
* Unfortunately the Zenodo Sandbox is giving 500 Server Errors right now when we attempt to download an existing record ID, but that's independent of this PR.
* All the other tests seem to pass.
```[tasklist]
```
> Update pudl-archiver to use Frictionless v5

- src/pudl_archiver/archivers/ferc/ferc6.py
- src/pudl_archiver/archivers/ferc/ferc714.py
- src/pudl_archiver/depositors/depositor.py
- src/pudl_archiver/orchestrator.py
- tests/integration/zenodo_test.py
This PR cleans up some minor bugs introduced in recent changes. It fixes auto-publishing behavior, which was publishing even when disabled, and fixes ferc 6/714 archivers, which were calling the `archive_taxonomy` function slightly incorrectly.
> Fix auto publish and ferc 6/714 archivers

- src/pudl_archiver/archivers/ferc/ferc1.py
- src/pudl_archiver/archivers/ferc/ferc6.py
- src/pudl_archiver/archivers/ferc/ferc60.py
- src/pudl_archiver/archivers/ferc/ferc714.py
- src/pudl_archiver/depositors/depositor.py
- tests/integration/zenodo_test.py
This PR addresses issues discovered while trying to publish new archives outlined in [this](https://github.com/catalyst-cooperative/pudl-archiver/issues/336) issue. Specifically, it addresses problems with the `datapackage.json` files generated during this run, and problems with the FERC archivers. The datapackage issues arose fromrecent updates that caused us to accidentally overwrite values in the file causing there to be bad links for resources within the archive. The [FERC issue](https://github.com/catalyst-cooperative/pudl-archiver/issues/338) came up when we started occasionally getting errors where we would get a webpage that appeared to be a logon while trying to archive taxonomy files. This appears to be a rate limiting mechanism, and by reducing concurrency, we were able to …
> Fix datapackage errors and FERC failures

- README.md
- src/pudl_archiver/cli.py
- src/pudl_archiver/depositors/depositor.py
- src/pudl_archiver/utils.py
- tests/integration/zenodo_test.py
Closes #208.
The `--dry-run` option does not adequately simulate running the archiver, so it's better to rely on the `--auto-publish` option.
I removed all references to the --dry-run option.
To find all references to the flag I searched the repository for "dry".
I was not able to run any tests because the dependencies currently have a conflict. This repo stipulates `"ruff>=0.3,<0.4"` but the `pudl` repository [recently](https://github.com/catalyst-cooperative/pudl/commit/5806b46c7c5efe367bb06045d78417f9c51c3134) updated `ruff` to 4.1.
Let me know if there are any testing steps I should take!
```[tasklist]
```
> Remove --dry-run CLI option and references

- .github/workflows/tox-pytest.yml
- environment.yml
- pyproject.toml
- tox.ini
GDAL 3.9.0 has been out for a while, but the dependency between PUDL and the archivers kept us from updating.  Trying to resolve these incompatibilities in this PR.
I think that [the PUDL PR](https://github.com/catalyst-cooperative/pudl/pull/3668) updating the dependency needs to merge before the CI on this PR can pass.
```[tasklist]
```
> Bump GDAL to 3.9.0 explicitly to align with PUDL dependencies

- .github/ISSUE_TEMPLATE/monthly-archive-update.md
- .github/workflows/run-archiver.yml
- scripts/make_slack_notification_message.py
Addresses subset of #346 and #347, focusing on the lowest hanging improvements.
There are two types of GHA failures we want to keep track of: run failures and validation test failures. These should both be reported in the Slackbot notifications. The archive run now also automatically opens an issue using the archive issue template, noting the date of the run and linking to the URL for the action. Finally, we can now easily configure what datasets we run on a manual workflow dispatch, whether to kick off the large runner for EPACEMS (and eventually maybe some other datasets), and whether to make a Github issue following the run.
Out of scope:
- Figure out how to add other run failures to Slack message with enough info from the …
> MVP improvements to automated archive runs

- environment.yml
The main PUDL repo now requires `geopandas>=1.0` which does no longer depends on `fiona` so we don't need to install it in the conda environment for this repo anymore (hopefully all the other geospatial stuff behaves itself!)
```[tasklist]
```
> Remove outdated fiona dependency (as of geopandas v1.0)

- src/pudl_archiver/archivers/nrelatb.py
- src/pudl_archiver/package_data/zenodo_doi.yaml
Closes #369.
Updates NREL ATB and EIA AEO data from #369. Both records had a problem with concept DOIs marked as "deleted" incorrectly in the Zenodo API.
- Add 2024 NREL ATB data
- Move badly located NREL ATB archiver (out of EIA folder)
- Add temporary reference to the record rather than the troublesome deleted API for EIA AEO data, to enable future runs until issue is fixed.
NREL archive is [here](https://zenodo.org/records/12609821).
You can try running either the AEO or NREL archivers, both should now work.
```[tasklist]
```
> July data update: Move NREL ATB, include 2024 data, make AEO doi work

- .github/ISSUE_TEMPLATE/early-final-release-template.md
- .github/workflows/early_final_release_checker.yml
Addresses first part of #372.
We currently don't have a regular way of checking what day ER and FR data are released. This PR makes a new GHA workflow that runs the archivers every day in June and July (looking for ER data) and September and October (looking for FR data). This currently only runs on 860, 861 and 923.
Made a new GHA workflow and corresponding issue template.
Once merged into main, we should run the workflow manually and check that it has kicked off the expected archives, and created the expected issue. We'll need to do this in order to be able to run the workflow without implementing some `on: push` workaround (e.g., as discussed …
> Add GHA template to check early and final release data daily in release months, create issue

- src/pudl_archiver/archivers/eia/eia176.py
- src/pudl_archiver/archivers/nrelatb.py
Addresses part of #372.
With hardcoded years, we currently have to remember to check whether a new year of data is out. The monthly archiver runs won't capture new years of data released.
Removes hardcoded year from NREL ATB and EIA 176 archivers. 
Run both archivers. Verify all years expected to download are successfully downloaded.
```[tasklist]
```
> Update 176 and ATB archivers to not hardcode year

- src/pudl_archiver/archivers/eia/eia923.py
Closes first step of https://github.com/catalyst-cooperative/pudl/issues/3677.
EIA 923 data has an early release in July. The archiver currently doesn't capture files which include the early release prefix "er", unlike the EIA 860 and 861 archivers. This has caused a failure in this morning's archive run: https://github.com/catalyst-cooperative/pudl-archiver/actions/runs/9870803976
Added the er prefix as an optional group in the 923 archiver regex.
See the draft EIA 923 archive in Zenodo.
```[tasklist]
```
> Add ER prefix to 923 archiver

- src/pudl_archiver/package_data/zenodo_doi.yaml
In #370, we updated the AEO DOI to reference the latest record, rather than the concept DOI, which was incorrectly marked as "deleted" in Zenodo's API interface. This has now been fixed, and we should revert to using the concept DOI.
Updated the DOI in `zenodo_doi.yaml` back to the concept DOI.
Try to run `pudl_archiver --dataset eiaaeo --sandbox` and see if it works!
```[tasklist]
```
> Update EIA AEO DOI back to concept DOI

- .github/ISSUE_TEMPLATE/early_release_checker.md
- .github/workflows/run-archiver.yml
- src/pudl_archiver/archivers/ferc/xbrl.py
- src/pudl_archiver/cli.py
- src/pudl_archiver/depositors/depositor.py
- src/pudl_archiver/depositors/zenodo/depositor.py
- src/pudl_archiver/orchestrator.py
- src/pudl_archiver/package_data/zenodo_doi.yaml
- src/pudl_archiver/utils.py
- tests/integration/zenodo_test.py
First part of changes for #418.
- Fixes AEO archiver due to return of delete DOI error (see #412, #398).
- Sorts FERC taxonomies to try and avoid changes in sorting marked as partition updates
- Returns delete_deposition method and adds it as default to small runs of the archiver. Leave the draft for CEMS and other future big runner archives, as it's a long and slow run. Add this method to the integration tests.
Run an archive with no changes and with/without `--clobber-unchanged` (e.g. `epacamd_eia`). Should delete a draft when clobbering, and should leave a draft when not clobbering.
```[tasklist]
```
> Restore delete_deposition method, update AEO doi, sort FERC taxonomies

- src/pudl_archiver/archivers/ferc/xbrl.py
- src/pudl_archiver/archivers/validate.py
- tests/unit/archive_validate_test.py
- tests/unit/ferc_archiver_test.py
Closes #399.
FERC XBRL resources have been marked as changed even when there don't appear to be actual changes. There seem to have been two primary causes of these changes:
1. XBRL archives have a partition key called `taxonomies_referenced` which lists any taxonomy referenced by filings in a year of data. These have been marked as changed when only the order of the list has actually changed.
2. XBRL archives contain an rssfeed metadata json file which has also been changed due to the ordering of filings in the json.
This PR addresses both of these issues:
1. When comparing partition key value pairs, sort any values that are of type `list`
2. Sort keys in metadata json before writing to zipfile
Problem `1.` is easy to test by creating a new archive and looking at the summary to see that …
> Fix erroneous FERC XBRL updates

- .github/workflows/run-archiver.yml
There was a syntax error in the JSON that we feed into the monthly archive script as a matrix and so it failed to run November 1st. This PR literally adds a single character to that JSON blob to double-quote `"ferc1"`.
I've kicked off a `workflow_dispatch` run manually it seems to be running as expected.
> Fix quoting error in workflow file

- .github/workflows/early_final_release_checker.yml
- .github/workflows/run-archiver.yml
- scripts/make_slack_notification_message.py
Update our usage of `slack-github-action` to be compatible with the new v2.0 of that action.
The same action failed in the main PUDL repo and this fix worked there. Just updating the syntax here. Have not actually tested (but the old way would definitely fail).
> Fix slack GitHub action

- src/pudl_archiver/frictionless.py
- Use `exclude_none=True` in the `model_dump()` that we call when serializing the contributor class to generate a new Data Package to avoid outputting `null` values into `datapackage.json`
- Also replace deprecated `datetime.utcnow()` funciton with recommended code.
Figured out while messing around with https://github.com/catalyst-cooperative/pudl/pull/3969
Closes catalyst-cooperative/pudl#3005
* Ran the unit and integration tests locally.
* Ran the `eia860m` archiver on the branch to see if we could create a successful draft archive / `datapackage.json`
```json
"contributors": [
{
"title": "Catalyst Cooperative",
"path": "https://catalyst.coop/",
"email": "pudl@catalyst.coop",
"role": "publisher",
"zenodo_role": "distributor",
"organization": "Catalyst Cooperative",
"orcid": null
}
``` …
> Exclude null values from contributor serialization

- environment.yml
All this does is bump the version of the binary `gdal` dependency to match what we have in the main PUDL repo, since they need to remain synchronized.
This PR should not be merged until https://github.com/catalyst-cooperative/pudl/pull/4010 has merged.
> Bump gdal version to match main PUDL repo

- .github/workflows/run-archiver.yml
We sometimes get archivers published shortly after our monthly archive run, and we may want a more granular update on changes in any data archive. However, we have budget for a monthly update of our archivers, so we don't necessarily want to be publishing all of our archives each week as changes occur.
- Add a second cron schedule that runs all our archivers every Monday at 8:21 AM UTC
- This schedule _does not_ create a new Github archive - it's purely for informational purposes, and we can decide to create a Github issue / publish these archives on an as-needed basis, rather than having to close a Github issue each week.
This will require merging to main to …
> Add a weekly archiver run on Mondays that doesn't create a Github issue

- src/pudl_archiver/archivers/censusfips.py
- src/pudl_archiver/archivers/censuspep.py
- src/pudl_archiver/archivers/classes.py
- src/pudl_archiver/archivers/eia/eia860m.py
- src/pudl_archiver/archivers/eia/eia930.py
- src/pudl_archiver/archivers/epacems.py
- src/pudl_archiver/cli.py
- src/pudl_archiver/frictionless.py
- src/pudl_archiver/package_data/zenodo_doi.yaml
working on https://github.com/catalyst-cooperative/pudl/issues/3884
- this adds an archiver which grabs that county level fips codes from the census
- i added an archiver module. I used the template in the readme and edited it mostly using patterns from the NREL ATB archiver
- I was surprised to have to add an `xls` media type. this was only required for the older files but i'm surprised we've never had to archive `xls` files. Did I miss something here?
- I had to do a semi-janky add of the [1990-2000/](https://www2.census.gov/programs-surveys/popest/geographies/1990-2000/).. txt file. 
- (i also added census metadata in pudl - i will link make that pr and link to it here)
How did you make sure this worked? How can a reviewer …
> Make census fips codes archiver

- .github/workflows/run-archiver.yml
- .gitignore
- src/pudl_archiver/archivers/usgsuspvdb.py
- src/pudl_archiver/cli.py
- src/pudl_archiver/package_data/zenodo_doi.yaml
Closes https://github.com/catalyst-cooperative/pudl-archiver/issues/515
Taking over from #535.
Adding USGS PV database to our archiving workflows.
Added a new subclass of `AbstractDatasetArchiver` called usgsuspvdb.py. Also fixed a personal annoyance and sorted the list of archivers in the CLI help function to make it easier to find what you're misspelling.
Published sandbox DOI is here for review: https://sandbox.zenodo.org/records/157777
The 2023 publication contains data up through 2021, so I've used `{year = 2021}` in line with how we treat the majority of our datasets. And 2024 -> data up through 2023. Does this make sense to you, reviewer?
```[tasklist] …
```
> Archive USGS PV database

- README.md
- src/pudl_archiver/cli.py
Closes #553.
* Add `--list` CLI option which prints each archiver name and then exits
* Update README to list a few sample archivers and then direct user to `--list` to see the rest.
```bash
$ pudl_archiver --list
[...]
$ pudl_archiver --help | grep list
```
```[tasklist]
```
> Add --list option to CLI to print the names of all available archivers

- .pre-commit-config.yaml
Switch to using a different mirror of the `prettier` pre-commit hook that is actually being maintained.
I ran the `prettier` pre-commit hook on all files locally and it didn't do anything unexpected.
> Switch to a new prettier mirror and bump ruff pre-commit hook.

- src/pudl_archiver/archivers/classes.py
Closes #XXXX.
- Hyperlink extractor does not return URLs in tags other than `<a>` tags
- Hyperlink extractor also does not return information inside the tags, which could contain the actual filename, e.g. `<a href="...">filename.zip</a>`
- In the case of the new data archiver https://github.com/catalyst-cooperative/pudl-archiver/pull/539 the name would be needed for extracting properties such as dataset upload date.
- Hyperlink extractor returns all hyperlinks (based on some list of attributes rather than only the href attribute in the <a> tag)
- Return value is dict instead of set, with values {hyperlink: name} where name contains the text between tags, if present, and defaults to hyperlink itself.
- Check for name matches …
> generalize hyperlink extractor

- src/pudl_archiver/archivers/eia/eia176.py
- src/pudl_archiver/archivers/eia/eia930.py
- src/pudl_archiver/archivers/eia/eiamecs.py
- src/pudl_archiver/archivers/eia/eianems.py
- src/pudl_archiver/archivers/eia/eiawater.py
- src/pudl_archiver/archivers/eia/naturalgas.py
- src/pudl_archiver/archivers/epa/epacems.py
- src/pudl_archiver/archivers/epa/epamats.py
- src/pudl_archiver/archivers/gridpathratoolkit.py
- src/pudl_archiver/archivers/mshamines.py
- src/pudl_archiver/archivers/phmsagas.py
- src/pudl_archiver/archivers/vcerare.py
Closes #XXXX.
- Small cleanup to use abstract archiver class' logger instead of importing when relevant
```[tasklist]
```
> cleanup logging using class defined logger

- .github/workflows/initialize-archiver.yml
Makes the choice of server more obvious in `initialize-archiver`
- Switch from boolean to choice in github action
Run the action on this branch for both production and sandbox servers.
Sandbox: https://github.com/catalyst-cooperative/pudl-archiver/actions/runs/13168342804/job/36753639628
Prod: https://github.com/catalyst-cooperative/pudl-archiver/actions/runs/13168368880/job/36753714104
```[tasklist]
```
> Make server selection on `initialize-archiver` clearer

- src/pudl_archiver/archivers/classes.py
- src/pudl_archiver/archivers/nrelss.py
- src/pudl_archiver/metadata/sources.py
Closes #561.
* NREL Standard Scenarios data is not available for download from static links, only from a javascript-powered web app
* We reverse engineered the API calls made by the web app and reproduce them here; they're basic GET and POST requests with no credentials necessary
* Add options for POST to `pudl_archiver.archivers.classes._download_file()` and `pudl_archiver.archivers.classes.AbstractDatasetArchiver.download_file()`
* Split hyperlink extraction in `pudl_archiver.archivers.classes.AbstractDatasetArchiver` into two phases to permit extraction of links directly from an HTML string
* New archiver for NREL Standard Scenarios
Ran locally in fsspec …
> Add archiver for NREL Standard Scenarios

- src/pudl_archiver/archivers/ferc/xbrl.py
- tests/unit/ferc_archiver_test.py
in the standard monthly archiving process ella published a new ferc1 zenodo archive today. we decided to try to integrate it into pudl to work out integration kinks even though rn it looks like ~80% of the utilities have responded. and I’ve found the first  road block, but then i think it's fixed.
it looks like in the past archives the `rssfeed` files for each year are dictionaries. in this most recent archive the `rssfeed`  is just a list of respondents. it looks like this got changed ~7 months ago w/ a small fix. But the dictionary was being `sorted` which converted this into a list of just the filer names instead of the full dictionary.
kept sorting the dictionary but just used `sorted` to sort all of the keys.
Questions? …
> smol xbrl rssfeed fix (sorted was converting rssfeed dictionary to a list)

- .github/workflows/run-archiver.yml
- README.md
- src/pudl_archiver/depositors/depositor.py
- src/pudl_archiver/depositors/fsspec.py
- src/pudl_archiver/depositors/zenodo/depositor.py
- tests/integration/zenodo_test.py
Closes #458.
_What problem does this address?_
Sometimes Zenodo returns a 502, and when that happens, sometimes the file Zenodo keeps is incomplete.
_What did you change in this PR?_
* Add code to `DraftDeposition._apply_change` that verifies the checksum of the uploaded file matches the checksum of the local file. If not, retry up to 5 times before raising an exception.
* Add abstract method `get_checksum` to `DraftDeposition`, and implementations in the zenodo and fsspec subclasses (this helps us avoid having to pass the reference checksum through a bunch of nested functions)
* Add integration test to verify intended behavior in the event of a nonmatching remote checksum
* Update misleading docstrings discovered during the quest
Specifically hoping for input on:
_How did you make sure …
> Ensure uploaded files match local checksums (502 mitigation)

- .pre-commit-config.yaml
Prefix our local unit test pre-commit hook with `pixi run` so that it Just Works.
Closes #694 
It seemed to work when I made the commit for this PR!
> Use pixi run to run unit test pre-commit hook
